---
abstract: 'Perl Development and Testing network.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDT
provides:
  PDT:
    file: lib/PDT.pm
    version: 0.001
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
